# Generated by Django 2.1.3 on 2018-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='anho',
            new_name='año',
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default='CC4401', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.CharField(choices=[('primavera', 'Primavera'), ('otoño', 'Otoño'), ('verano', 'Verano')], default='Otoño', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo', 'seccion', 'año', 'semestre')},
        ),
    ]
