# Generated by Django 2.1.3 on 2018-11-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante_curso',
            name='rol',
            field=models.CharField(choices=[('Ayudante', 'Ayudante'), ('Profesor/a', 'Profesor/a'), ('Auxiliar', 'Auxiliar'), ('Estudiante', 'Estudiante')], max_length=20),
        ),
    ]
