# Generated by Django 2.1.3 on 2018-11-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coev', '0002_auto_20181117_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.CharField(choices=[('Primavera', 'Primavera'), ('Otoño', 'Otoño'), ('Verano', 'Verano')], default='Primavera', max_length=30),
        ),
    ]
